PROJECT_NAME := rosem-esp32

MY_PATH := $(abspath $(dir $(firstword $(MAKEFILE_LIST))))

COMPONENT_DIRS := $(IDF_PATH)/components $(MY_PATH)/../../husarnet/common $(MY_PATH) $(MY_PATH)/..

include $(IDF_PATH)/make/project.mk
